version: "3"

services:
  db:
    image: mysql:8.3
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    command: --collation-server=utf8mb4_general_ci

  app:
    build:
      # Dockerfileを格納するフォルダのパス
      context: ./docker/app
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  web:
    image: nginx:1.25.0
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-store:
    driver: local